version: "3.8"
name: "foodserver"
services:
  essen-webserver:
    build:
      context: ./
      dockerfile: ./docker/PHP/Dockerfile
    ports:
      - "8080:80"
    environment:
      APP_ENV: dev
            
  essen-dbserver:
    build: 
      context: ./
      dockerfile: ./docker/DB/Dockerfile
    volumes:
      - essenDB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    # ports:
    #   - "3306:3306"

volumes:
  essenDB:

