version: "3.7"
name: "foodserver"
services:
  webserver:
    image: essen-app
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql://root:abc123@mariadb:3306/ovm_Essens-bersichtswebseite?serverVersion=mariadb-10.8.3
            
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - essenDB:/var/lib/mysql
    # ports:
    #   - "3306:3306"

volumes:
  essenDB:

