version: "3.8"
name: "foodserver"
services:
  essen-php:
    build:
      context: ./
      dockerfile: ./docker/PHP/Dockerfile
    expose:
      - "9000"
    environment:
      APP_ENV: prod
    volumes:
      - www:/var/www/
    depends_on:
      - essen-dbserver

  essen-nginx:
    build: 
      context: ./docker/NGINX
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - www:/var/www/
    depends_on:
      - essen-php
            
  essen-dbserver:
    build: 
      context: ./docker/DB
      dockerfile: ./Dockerfile
    volumes:
      - essenDB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    # ports:
    #   - "3306:3306"

volumes:
  www:
  essenDB:

